#!/bin/sh

which screen > /dev/null
if [ $? -ne 0 ]; then
    echo Unable to locate screen, aborting.
    exit
fi

if [ -z "$SSH_AGENT_PROXY_SOCKET" ]; then
    export SSH_AGENT_PROXY_SOCKET=`ssh-agent-proxy.pl -p -e -i`
    if [ $? -ne 0 ]; then
        echo Error starting ssh-agent-proxy.pl, aborting.
        exit
    fi
fi
export SSH_AUTH_SOCK=$SSH_AGENT_PROXY_SOCKET
exec screen $*
